### ISSUE TITLE
Seems not to work with M2 2.1.4

### ISSUE THREAD

**Issue by kkrieger85** [mageplaza/Magento-2-Social-Login-Extension#11]
Error in Backend:
```
1 exception(s):
Exception #0 (OutOfRangeException): Specified invalid parent id (Mageplaza_Core::menu)

Exception #0 (OutOfRangeException): Specified invalid parent id (Mageplaza_Core::menu)
#0 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Backend\Model\Menu\Builder->getResult(Object(Magento\Backend\Model\Menu))
#1 /var/www/magento2/var/generation/Magento/Backend/Model/Menu/Builder/Interceptor.php(39): Magento\Backend\Model\Menu\Builder\Interceptor->___callPlugins('getResult', Array, Array)
#2 /var/www/magento2/vendor/magento/module-backend/Model/Menu/Config.php(146): Magento\Backend\Model\Menu\Builder\Interceptor->getResult(Object(Magento\Backend\Model\Menu))
#3 /var/www/magento2/vendor/magento/module-backend/Model/Menu/Config.php(109): Magento\Backend\Model\Menu\Config->_initMenu()
#4 /var/www/magento2/vendor/magento/module-backend/Model/Url.php(348): Magento\Backend\Model\Menu\Config->getMenu()
#5 /var/www/magento2/vendor/magento/module-backend/Model/Url.php(308): Magento\Backend\Model\Url->_getMenu()
#6 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(273): Magento\Backend\Model\Url->getStartupPageUrl()
#7 /var/www/magento2/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(50): Magento\Backend\App\AbstractAction->_processUrlKeys()
#8 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(205): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->_processUrlKeys()
#9 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#11 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#12 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#15 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento2/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /var/www/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#21 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#22 /var/www/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#27 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#28 {main}
```

Error in Frontend:
```
( ! ) Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/magento2/vendor/mageplaza/magento-2-social-login/Helper/Data.php on line 13
```

Social-Login-Version (Snippet from composer.lock
```
       {
            "name": "mageplaza/magento-2-social-login",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/mageplaza/Magento-2-Social-Login-Extension.git",
                "reference": "9f5e725e2340c4dd5ac271f8794f6e33ed82989f"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/mageplaza/Magento-2-Social-Login-Extension/zipball/9f5e725e2340c4dd5ac271f8794f6e33ed82989f",
                "reference": "9f5e725e2340c4dd5ac271f8794f6e33ed82989f",
                "shasum": ""
            },
            "require": {
                "php": "~5.5.0|~5.6.0|~7.0.0"
            },
            "type": "magento2-module",
            "autoload": {
                "files": [
                    "registration.php"
                ],
                "psr-4": {
                    "Mageplaza\\SocialLogin\\": ""
                }
            },
            "license": [
                "OSL-3.0",
                "AFL-3.0"
            ],
            "authors": [
                {
                    "name": "Mageplaza",
                    "email": "hi@mageplaza.com",
                    "homepage": "https://www.mageplaza.com",
                    "role": "Leader"
                }
            ],
            "description": "Magento 2 Social Login Extension",
            "support": {
                "source": "https://github.com/mageplaza/Magento-2-Social-Login-Extension/tree/master",
                "issues": "https://github.com/mageplaza/Magento-2-Social-Login-Extension/issues"
            },
            "time": "2016-12-20 03:47:26"
        },
```

Magento2 Version

```
        "magento/product-community-edition": "2.1.4",
```

**Comment by kkrieger85** [comment]
Your module seems to need https://github.com/mageplaza/core-m2 

Solution could be to add core-m2 to composer.json requirements. 

Will test it

**Comment by kkrieger85** [comment]
After installation of core-m2, all errors are gone. 

Please add core-m2 to dependencies

**Comment by imsamthomas** [comment]
@kkrieger85 thanks for your suggestion.
I added required field in composer.json file
